AB#18 AB#19 AB#20 - PR
minhman97/SnipMan pull request #1
Opened 2023-06-07 11:06 UTC by minhman97

[AB#18](https://dev.azure.com/minhmancarter/7844c8b2-5ce7-4cec-baf2-5a3248015162/_workitems/edit/18) [AB#19](https://dev.azure.com/minhmancarter/7844c8b2-5ce7-4cec-baf2-5a3248015162/_workitems/edit/19) [AB#20](https://dev.azure.com/minhmancarter/7844c8b2-5ce7-4cec-baf2-5a3248015162/_workitems/edit/20)

2023-06-08 04:31 UTC, popemkt commented on BackEnd/Dockerfile
> +RUN dotnet restore --disable-parallel
Remove --disable-parallel

2023-06-08 04:35 UTC, popemkt commented on BackEnd/SnippetManagement.Api/Program.cs
> +            policy.WithOrigins("http://localhost:5002", "http://localhost:3000")
No debug values

2023-06-08 06:05 UTC, popemkt requested changes, later dismissed

2023-06-08 06:05 UTC, popemkt commented on BackEnd/SnippetManagement.Service/Services/Implementation/AuthenticationService.cs
> +            return Result.Ok().WithSuccess(tokenHandler.WriteToken(securityToken));
Incorrect use of Result Class

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/Dockerfile
> +RUN npm run build -- --profile
CRA already supports production build with build cmd

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/Dockerfile
> +RUN npm install --silent --force
no need for silent

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/src/api/ApiEndpoint.js
> +export const baseUrl = process.env.REACT_APP_BASE_URL;
Should centralize all urls here

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/src/api/ProgramingLanguageApi.js
> +  return await fetch(`${baseUrl}ProgramingLanguage/GetLanguage`, {
Fix this endpoint naming => REST

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/src/api/UserApi.js
> +};
Doesn't belong to API

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/src/api/StatusCode.js
>  export const GetErrorMessage = (statusCode) => {
Need more suitable name

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/src/components/LoginForm.js
> +  const [Auth, setAuth] = useState({ isAuth: false, message: "" });
Auth no Cap
Should use null to indicate no value

2023-06-08 06:05 UTC, popemkt commented on FrontEnd/snippet_management.web/src/routes/Snippet/Snippet.js
> +  const { mutate: muatateDeleteSnippet } = useDeleteSnippet();
fix typo

2023-06-08 06:05 UTC, popemkt commented on docker-compose.yml
> +      MSSQL_SA_PASSWORD: MyPassword123!
Should be variable

2023-06-08 06:05 UTC, popemkt commented on docker-compose.yml
> +      REACT_APP_GOOGLE_CLIENT_ID: 448086775090-g62vpn8qbig7gqt2qiin9m6ok5sgislk
Should be variable

2023-06-08 06:05 UTC, popemkt commented on docker-compose.yml
> +      Jwt__IssuerSigningKey: ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM
Should be variable

2023-06-08 10:50 UTC, minhman97 commented on BackEnd/SnippetManagement.Api/Controllers/AuthenticationController.cs
> +            return BadRequest(result);
Fix this

2023-06-08 10:50 UTC, minhman97 commented on BackEnd/SnippetManagement.Api/Controllers/SnippetController.cs
>          var userId = User.Claims.Where(c => c.Type == "UserId")
Refactor this into IdentityService.GetCurrentUserId()

2023-06-08 10:50 UTC, minhman97 commented on docker-compose.yml
> +      WEB_PORT: ${WEB_PORT}
Rename following .net config convention

2023-06-08 10:50 UTC, minhman97 commented on FrontEnd/snippet_management.web/src/api/ApiEndpoint.js
> +export const searchSnippetUrl = (
merge into 1 method

2023-06-08 10:50 UTC, minhman97 commented on FrontEnd/snippet_management.web/src/components/SnippetList.js
>                                baseUrl +
Move to correct location

2023-06-08 10:50 UTC, minhman97 commented on FrontEnd/snippet_management.web/src/hooks/SnippetHooks.js
Rename

2023-06-08 10:50 UTC, minhman97 commented on FrontEnd/snippet_management.web/src/routes/Snippet/CreateSnippet.js
> +                        src={`${baseUrl}/${language.url}`}
move to correct location

2023-06-08 10:50 UTC, minhman97 commented on docker-compose.yml
> +      - '${WEB_PORT}:3000'
Make this variable as well

2023-06-08 10:50 UTC, minhman97 commented on docker-compose.yml
> +      - '5000:1433'
Make this variable as well

2023-06-12 02:18 UTC, minhman97 commented on BackEnd/SnippetManagement.Api/Controllers/AuthenticationController.cs
> +            return BadRequest(new { isFailed = result.IsFailed, message = result.Reasons.FirstOrDefault() });
No need for isFailed status

2023-06-12 02:19 UTC, minhman97 commented on BackEnd/SnippetManagement.Api/Controllers/SnippetController.cs
> +    private IIdentityService identityService;
Fix this

2023-06-12 02:20 UTC, minhman97 commented on BackEnd/SnippetManagement.Api/Program.cs
> +Console.WriteLine("checking URL Port: " + builder.Configuration["WEB_PORT"]);
Remove this

2023-06-12 02:21 UTC, minhman97 commented on BackEnd/SnippetManagement.Api/Program.cs
> +    FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "Assets")),
Assets as config value

2023-06-12 02:31 UTC, minhman97 commented on BackEnd/SnippetManagement.DataModel/User.cs
>  public class User: BaseEntity<Guid>
Space

2023-06-12 02:35 UTC, minhman97 commented on BackEnd/SnippetManagement.Service/Services/Implementation/AuthenticationService.cs
> +    public async Task<Result<string>> GetToken(UserDto userDto, string externalToken)
exToken nullable

2023-06-12 02:45 UTC, minhman97 commented on BackEnd/SnippetManagement.Service/Services/Implementation/AuthenticationService.cs
> +    public async Task<Result<string>> GetToken(UserDto userDto, string externalToken)
Refactor this, best to separate validation logic from business logic

2023-06-12 02:47 UTC, minhman97 commented on FrontEnd/snippet_management.web/src/api/ApiEndpoint.js
> +  return filterKeyWord.trim() === ""
Duplicate string

2023-06-12 02:55 UTC, popemkt approved these changes

2023-06-12 02:57 UTC, merged